import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Stars from './(stars)/stars'
import Header from './(header)/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'SWAPI Visualizer',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Stars></Stars>
        <Header></Header>
        {children}
      </body>
    </html>
  )
}
